name: My Envio Indexer
networks:
- id: 10
  start_block: 115319405
  contracts:
  - name: HappyRedPacket
    address:
    - 0x62E8cf62Dc0B7d7afF9A1A58CeA14976fDB16a85
    handler: src/EventHandlers.ts
    events:
    - event: ClaimSuccess(bytes32 id, address claimer, uint256 claimed_value, address token_address, bytes32 lock)
    - event: CreationSuccess(uint256 total, bytes32 id, string name, string message, address creator, uint256 creation_time, address token_address, uint256 number, bool ifrandom, uint256 duration, bytes32 lock)
    - event: RefundSuccess(bytes32 id, address token_address, uint256 remaining_balance, bytes32 lock)
